// domain: applicants (application lifecycle: create, draft, submit, withdraw, claim)
import type { Operation } from '../operation.js';
import { reqStr } from '../operation.js';
import { obj, uuid, isoDate, okResult } from '../schemas.js';

export const applicantsOps: Operation[] = [
  {
    domain: 'applicants',
    opId: 'application.create_self',
    method: 'POST',
    path: '/applications',
    auth: 'user',
    summary: 'Applicant self-creates an application (and applicant record on first use).',
    fn: 'fn_create_self_application',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.course_id, 'course_id'),
      reqStr(ctx.body.dob, 'dob'),
      reqStr(ctx.body.gender, 'gender'),
      reqStr(ctx.body.district, 'district'),
      ctx.body.block ?? null,
      ctx.body.address ?? null,
      ctx.body.qualification ?? null,
    ],
    request: obj(
      {
        course_id: uuid,
        dob: isoDate,
        gender: { type: 'string', enum: ['F', 'M', 'O'] },
        district: { type: 'string' },
        block: { type: 'string', nullable: true },
        address: { type: 'string', nullable: true },
        qualification: { type: 'string', nullable: true },
      },
      ['course_id', 'dob', 'gender', 'district'],
    ),
    response: obj({ application_id: uuid, applicant_id: uuid, status: { type: 'string' } }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.ALREADY_ACTIVE', 'E.VAL.FAILED'],
    notes: 'Enforces one active application per applicant (ux_applications_active).',
  },
  {
    domain: 'applicants',
    opId: 'application.create_assisted',
    method: 'POST',
    path: '/applications/assisted',
    auth: 'user',
    summary: 'Operator creates an assisted application for a walk-in applicant.',
    fn: 'fn_create_assisted_application',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.course_id, 'course_id'),
      reqStr(ctx.body.full_name, 'full_name'),
      reqStr(ctx.body.phone, 'phone'),
      reqStr(ctx.body.dob, 'dob'),
      reqStr(ctx.body.gender, 'gender'),
      reqStr(ctx.body.district, 'district'),
      ctx.body.block ?? null,
      ctx.body.address ?? null,
      ctx.body.guardian_name ?? null,
      ctx.body.guardian_phone ?? null,
    ],
    request: obj(
      {
        centre_id: uuid,
        course_id: uuid,
        full_name: { type: 'string' },
        phone: { type: 'string' },
        dob: isoDate,
        gender: { type: 'string', enum: ['F', 'M', 'O'] },
        district: { type: 'string' },
        block: { type: 'string', nullable: true },
        address: { type: 'string', nullable: true },
        guardian_name: { type: 'string', nullable: true },
        guardian_phone: { type: 'string', nullable: true },
      },
      ['centre_id', 'course_id', 'full_name', 'phone', 'dob', 'gender', 'district'],
    ),
    response: obj({ application_id: uuid, applicant_id: uuid, eligibility_preview: { type: 'boolean' } }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE'],
    notes: 'Requires operator membership at centre (SEC-ASG-003, checked in fn).',
  },
  {
    domain: 'applicants',
    opId: 'application.save_draft',
    method: 'PATCH',
    path: '/applications/:id/draft',
    auth: 'user',
    summary: 'Save draft fields on a DRAFT application (owner or assisting operator).',
    fn: 'fn_save_draft',
    args: (ctx) => [reqStr(ctx.params.id, 'id'), ctx.body.fields ?? {}],
    paramsSchema: obj({ id: uuid }, ['id']),
    request: obj({ fields: { type: 'object' } }, ['fields']),
    response: obj({ saved: { type: 'boolean' }, eligibility_preview: { type: 'boolean' } }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
    notes: 'p_fields is a jsonb whitelist applied inside the function; no column access in API.',
  },
  {
    domain: 'applicants',
    opId: 'application.submit',
    method: 'POST',
    path: '/applications/:id/submit',
    auth: 'user',
    summary: 'Submit an application (eligibility + required-document gate, idempotent).',
    fn: 'fn_submit_application',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.id, 'id')],
    paramsSchema: obj({ id: uuid }, ['id']),
    response: obj({ status: { type: 'string' }, review: { type: 'boolean' } }),
    errors: [
      'E.RES.NOT_FOUND',
      'E.STATE.INVALID_TRANSITION',
      'E.STATE.ELIGIBILITY_FAILED',
      'E.VAL.FAILED',
      'E.CONFLICT.DUPLICATE',
    ],
    notes: 'Requires Idempotency-Key. Opens the verification case on success.',
  },
  {
    domain: 'applicants',
    opId: 'application.withdraw',
    method: 'POST',
    path: '/applications/:id/withdraw',
    auth: 'user',
    summary: 'Applicant withdraws a pre-decision application (cascades, idempotent).',
    fn: 'fn_withdraw_application',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.id, 'id'), reqStr(ctx.body.reason, 'reason')],
    paramsSchema: obj({ id: uuid }, ['id']),
    request: obj({ reason: { type: 'string' } }, ['reason']),
    response: obj({ status: { type: 'string' } }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'applicants',
    opId: 'applicant.claim_assisted',
    method: 'POST',
    path: '/applicants/claim',
    auth: 'user',
    summary: 'Claim an unclaimed assisted applicant record by matching phone (idempotent).',
    fn: 'fn_claim_assisted',
    idempotent: true,
    args: () => [],
    response: obj({ applicant_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE'],
    notes: 'Concurrency-safe: profile_id set once under row lock (SEC-CONC-004).',
  },
  {
    domain: 'applicants',
    opId: 'admission.reassign_assistance',
    method: 'POST',
    path: '/applications/:id/reassign-assistance',
    auth: 'user',
    summary: 'Centre admin hands a DRAFT application to another operator.',
    fn: 'fn_reassign_assistance',
    args: (ctx) => [
      reqStr(ctx.params.id, 'id'),
      reqStr(ctx.body.new_operator, 'new_operator'),
      reqStr(ctx.body.reason, 'reason'),
    ],
    paramsSchema: obj({ id: uuid }, ['id']),
    request: obj({ new_operator: uuid, reason: { type: 'string' } }, ['new_operator', 'reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  // --- reads ---
  {
    domain: 'applicants',
    opId: 'applications.list',
    method: 'GET',
    path: '/applications',
    auth: 'user',
    summary: 'List applications visible to the caller (RLS: owner / operator / staff / checker).',
    read: () => ({
      text: `SELECT id, applicant_id, centre_id, course_id, status, eligibility_flag,
                    hostel_required, submitted_at, created_at, updated_at
             FROM app.applications ORDER BY created_at DESC LIMIT 200`,
      values: [],
    }),
    notes: 'Rows scoped by policy p_applications_sel via DEFINER helpers.',
  },
  {
    domain: 'applicants',
    opId: 'application.get',
    method: 'GET',
    path: '/applications/:id',
    auth: 'user',
    summary: 'Get a single application by id (RLS-scoped).',
    read: (ctx) => ({
      text: `SELECT id, applicant_id, centre_id, course_id, status, eligibility_flag,
                    hostel_required, qualification, passing_year, submitted_at,
                    withdrawn_at, created_at, updated_at
             FROM app.applications WHERE id = $1`,
      values: [reqStr(ctx.params.id, 'id')],
      single: true,
    }),
    paramsSchema: obj({ id: uuid }, ['id']),
    errors: ['E.RES.NOT_FOUND'],
  },
];
