// domain: centre administration (staff, roles, config, exports, audit query)
import type { Operation } from '../operation.js';
import { reqStr } from '../operation.js';
import { obj, uuid, okResult, isoDate, isoDateTime } from '../schemas.js';

export const centreAdminOps: Operation[] = [
  {
    domain: 'centre-administration',
    opId: 'staff.create',
    method: 'POST',
    path: '/admin/staff',
    auth: 'service',
    summary: 'Provision a staff profile + membership ([SYS]; auth user created first).',
    fn: 'fn_staff_register',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.profile_id, 'profile_id'),
      reqStr(ctx.body.full_name, 'full_name'),
      ctx.body.email ?? null,
      reqStr(ctx.body.phone, 'phone'),
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.role, 'role'),
    ],
    request: obj(
      {
        profile_id: uuid,
        full_name: { type: 'string' },
        email: { type: 'string', nullable: true },
        phone: { type: 'string' },
        centre_id: uuid,
        role: { type: 'string' },
      },
      ['profile_id', 'full_name', 'phone', 'centre_id', 'role'],
    ),
    response: okResult,
    errors: ['E.CONFLICT.DUPLICATE'],
    notes: 'service_role. The API/EF creates the auth user, then passes its uuid as profile_id.',
  },
  {
    domain: 'centre-administration',
    opId: 'membership.grant',
    method: 'POST',
    path: '/admin/memberships/grant',
    auth: 'user',
    summary: 'Grant a role membership (CAD own-centre non-admin; SAD anywhere).',
    fn: 'fn_membership_grant',
    args: (ctx) => [
      reqStr(ctx.body.profile_id, 'profile_id'),
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.role, 'role'),
      reqStr(ctx.body.reason, 'reason'),
    ],
    request: obj(
      { profile_id: uuid, centre_id: uuid, role: { type: 'string' }, reason: { type: 'string' } },
      ['profile_id', 'centre_id', 'role', 'reason'],
    ),
    response: okResult,
    errors: ['E.RES.NOT_FOUND'],
  },
  {
    domain: 'centre-administration',
    opId: 'membership.revoke',
    method: 'POST',
    path: '/admin/memberships/revoke',
    auth: 'user',
    summary: 'Revoke a role membership (CAD own-centre non-admin; SAD anywhere).',
    fn: 'fn_membership_revoke',
    args: (ctx) => [
      reqStr(ctx.body.profile_id, 'profile_id'),
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.role, 'role'),
      reqStr(ctx.body.reason, 'reason'),
    ],
    request: obj(
      { profile_id: uuid, centre_id: uuid, role: { type: 'string' }, reason: { type: 'string' } },
      ['profile_id', 'centre_id', 'role', 'reason'],
    ),
    response: okResult,
    errors: ['E.RES.NOT_FOUND'],
  },
  {
    domain: 'centre-administration',
    opId: 'staff.deactivate',
    method: 'POST',
    path: '/admin/staff/:profileId/deactivate',
    auth: 'user',
    summary: 'Deactivate a staff member (offboarding; idempotent). Emits open-work event.',
    fn: 'fn_staff_deactivate',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.profileId, 'profileId'), reqStr(ctx.body.reason, 'reason')],
    paramsSchema: obj({ profileId: uuid }, ['profileId']),
    request: obj({ reason: { type: 'string' } }, ['reason']),
    response: obj({
      ok: { type: 'boolean' },
      open_cases: { type: 'integer' },
      open_drafts: { type: 'integer' },
    }),
    errors: ['E.RES.NOT_FOUND'],
    notes: 'Session revocation itself is an auth-provider concern (outside SQL).',
  },
  {
    domain: 'centre-administration',
    opId: 'config.set',
    method: 'PUT',
    path: '/admin/config/:key',
    auth: 'user',
    summary: 'Set a system setting (super_admin only).',
    fn: 'fn_config_set',
    args: (ctx) => [reqStr(ctx.params.key, 'key'), ctx.body.value, reqStr(ctx.body.reason, 'reason')],
    paramsSchema: obj({ key: { type: 'string' } }, ['key']),
    request: obj({ value: {}, reason: { type: 'string' } }, ['value', 'reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.VAL.FAILED'],
    notes: 'value is jsonb. SAD-only (checked in fn_config_set).',
  },
  {
    domain: 'centre-administration',
    opId: 'export.create',
    method: 'POST',
    path: '/admin/exports',
    auth: 'user',
    summary: 'Create an export job (centre_admin/super_admin/placement; idempotent).',
    fn: 'fn_export_create',
    idempotent: true,
    successStatus: 201,
    args: (ctx) => [reqStr(ctx.body.report_key, 'report_key'), ctx.body.params ?? {}],
    request: obj({ report_key: { type: 'string' }, params: { type: 'object' } }, ['report_key']),
    response: obj({ job_id: uuid }),
    errors: ['E.RES.NOT_FOUND'],
    notes: 'Generation + CSV-injection neutralization happen in the server/worker tier.',
  },
  {
    domain: 'centre-administration',
    opId: 'export.mark_downloaded',
    method: 'POST',
    path: '/admin/exports/:jobId/downloaded',
    auth: 'service',
    summary: 'Audit an export download ([SYS]).',
    fn: 'fn_export_mark_downloaded',
    args: (ctx) => [reqStr(ctx.params.jobId, 'jobId'), reqStr(ctx.body.actor, 'actor')],
    paramsSchema: obj({ jobId: uuid }, ['jobId']),
    request: obj({ actor: uuid }, ['actor']),
    response: obj({}),
    notes: 'service_role. Writes an export.downloaded audit row.',
  },
  {
    domain: 'centre-administration',
    opId: 'audit.query',
    method: 'GET',
    path: '/admin/audit',
    auth: 'user',
    summary: 'Query audit events (CAD centre-scoped / SAD all).',
    read: (ctx) => ({
      // fn_audit_query is DEFINER and self-scopes by the caller's role; call it as a
      // set-returning function rather than reading the closed audit_events table.
      text: `SELECT * FROM app.fn_audit_query($1, $2, $3, $4)`,
      values: [
        ctx.query.from ?? null,
        ctx.query.to ?? null,
        ctx.query.action ?? null,
        Number(ctx.query.limit ?? 100),
      ],
    }),
    querySchema: obj({
      from: { ...isoDateTime, nullable: true },
      to: { ...isoDateTime, nullable: true },
      action: { type: 'string', nullable: true },
      limit: { type: 'integer', minimum: 1, maximum: 500 },
    }),
    errors: ['E.RES.NOT_FOUND'],
    notes:
      'Backed by the DEFINER function fn_audit_query (centre scoping inside); the ' +
      'audit_events table itself has no client grant.',
  },
  // --- reads (catalogue) ---
  {
    domain: 'centre-administration',
    opId: 'centres.list',
    method: 'GET',
    path: '/centres',
    auth: 'user',
    summary: 'List active centres (authenticated).',
    read: () => ({
      text: `SELECT id, name, district, is_active FROM app.centres WHERE is_active ORDER BY name`,
      values: [],
    }),
    notes: 'Scoped by policy p_centres_sel.',
  },
  {
    domain: 'centre-administration',
    opId: 'staff.list',
    method: 'GET',
    path: '/admin/staff',
    auth: 'user',
    summary: 'List staff memberships at the caller’s centre(s) (centre admin) for assignment pickers.',
    read: () => ({
      // p_memb_sel scopes to the caller's own membership OR centres where they are
      // centre_admin/super_admin. profiles RLS is own-only, so no name is exposed here —
      // callers select by role_code + profile_id. Never trusts a browser-supplied centre.
      text: `SELECT profile_id, centre_id, role_code, is_active
             FROM app.staff_memberships WHERE is_active ORDER BY role_code, profile_id`,
      values: [],
    }),
    notes: 'Scoped by policy p_memb_sel.',
  },
  {
    domain: 'centre-administration',
    opId: 'batches.list',
    method: 'GET',
    path: '/batches',
    auth: 'user',
    summary: 'List batches (OPEN/RUNNING publicly to authenticated; all for own-centre staff).',
    read: () => ({
      text: `SELECT id, centre_id, course_version_id, code, capacity, start_date, end_date, status
             FROM app.batches ORDER BY start_date DESC LIMIT 200`,
      values: [],
    }),
    notes: 'Scoped by policy p_batches_sel.',
  },
  // --- catalogue CRUD (migration 0004) ---
  {
    domain: 'centre-administration',
    opId: 'course.create',
    method: 'POST',
    path: '/admin/courses',
    auth: 'user',
    summary: 'Create a course (super_admin only).',
    fn: 'fn_course_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.code, 'code'),
      reqStr(ctx.body.name_en, 'name_en'),
      reqStr(ctx.body.name_hi, 'name_hi'),
    ],
    request: obj({ code: { type: 'string' }, name_en: { type: 'string' }, name_hi: { type: 'string' } },
      ['code', 'name_en', 'name_hi']),
    response: obj({ course_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE', 'E.VAL.FAILED'],
    notes: 'SAD-only; courses are not centre-scoped.',
  },
  {
    domain: 'centre-administration',
    opId: 'course.set_active',
    method: 'PATCH',
    path: '/admin/courses/:courseId/active',
    auth: 'user',
    summary: 'Activate/deactivate a course (super_admin).',
    fn: 'fn_course_set_active',
    args: (ctx) => [reqStr(ctx.params.courseId, 'courseId'), ctx.body.active === true],
    paramsSchema: obj({ courseId: uuid }, ['courseId']),
    request: obj({ active: { type: 'boolean' } }, ['active']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND'],
  },
  {
    domain: 'centre-administration',
    opId: 'course.add_version',
    method: 'POST',
    path: '/admin/courses/:courseId/versions',
    auth: 'user',
    summary: 'Add a course version (super_admin).',
    fn: 'fn_course_version_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.params.courseId, 'courseId'),
      Number(ctx.body.version_no ?? 0),
      ctx.body.syllabus_summary ?? null,
      Number(ctx.body.duration_weeks ?? 0),
    ],
    paramsSchema: obj({ courseId: uuid }, ['courseId']),
    request: obj(
      {
        version_no: { type: 'integer', minimum: 1 },
        syllabus_summary: { type: 'string', nullable: true },
        duration_weeks: { type: 'integer', minimum: 1 },
      },
      ['version_no', 'duration_weeks'],
    ),
    response: obj({ course_version_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE', 'E.VAL.FAILED'],
  },
  {
    domain: 'centre-administration',
    opId: 'batch.create',
    method: 'POST',
    path: '/admin/batches',
    auth: 'user',
    summary: 'Create a batch (centre_admin at the centre).',
    fn: 'fn_batch_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.course_version_id, 'course_version_id'),
      reqStr(ctx.body.code, 'code'),
      Number(ctx.body.capacity ?? 0),
      reqStr(ctx.body.start_date, 'start_date'),
      reqStr(ctx.body.end_date, 'end_date'),
    ],
    request: obj(
      {
        centre_id: uuid,
        course_version_id: uuid,
        code: { type: 'string' },
        capacity: { type: 'integer', minimum: 1 },
        start_date: isoDate,
        end_date: isoDate,
      },
      ['centre_id', 'course_version_id', 'code', 'capacity', 'start_date', 'end_date'],
    ),
    response: obj({ batch_id: uuid, status: { type: 'string' } }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE', 'E.VAL.FAILED'],
  },
  {
    domain: 'centre-administration',
    opId: 'batch.update',
    method: 'PATCH',
    path: '/admin/batches/:batchId',
    auth: 'user',
    summary: 'Update batch fields (centre_admin; PLANNED/OPEN only).',
    fn: 'fn_batch_update',
    args: (ctx) => [reqStr(ctx.params.batchId, 'batchId'), ctx.body.fields ?? {}],
    paramsSchema: obj({ batchId: uuid }, ['batchId']),
    request: obj({ fields: { type: 'object' } }, ['fields']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.VAL.FAILED'],
  },
  {
    domain: 'centre-administration',
    opId: 'batch.set_status',
    method: 'POST',
    path: '/admin/batches/:batchId/status',
    auth: 'user',
    summary: 'Transition batch status (guarded: PLANNED→OPEN→RUNNING→COMPLETED / CANCELLED).',
    fn: 'fn_batch_set_status',
    args: (ctx) => [reqStr(ctx.params.batchId, 'batchId'), reqStr(ctx.body.status, 'status')],
    paramsSchema: obj({ batchId: uuid }, ['batchId']),
    request: obj(
      { status: { type: 'string', enum: ['OPEN', 'RUNNING', 'COMPLETED', 'CANCELLED'] } },
      ['status'],
    ),
    response: obj({ status: { type: 'string' } }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.VAL.FAILED'],
  },
  {
    domain: 'centre-administration',
    opId: 'notice.create',
    method: 'POST',
    path: '/admin/notices',
    auth: 'user',
    summary: 'Create a DRAFT notice (centre_admin).',
    fn: 'fn_notice_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.title_hi, 'title_hi'),
      reqStr(ctx.body.title_en, 'title_en'),
      reqStr(ctx.body.body_hi, 'body_hi'),
      reqStr(ctx.body.body_en, 'body_en'),
    ],
    request: obj(
      {
        centre_id: uuid,
        title_hi: { type: 'string' },
        title_en: { type: 'string' },
        body_hi: { type: 'string' },
        body_en: { type: 'string' },
      },
      ['centre_id', 'title_hi', 'title_en', 'body_hi', 'body_en'],
    ),
    response: obj({ notice_id: uuid, status: { type: 'string' } }),
    errors: ['E.RES.NOT_FOUND', 'E.VAL.FAILED'],
  },
  {
    domain: 'centre-administration',
    opId: 'notice.add_audience',
    method: 'POST',
    path: '/admin/notices/:noticeId/audiences',
    auth: 'user',
    summary: 'Add an audience to a DRAFT notice (centre_admin).',
    fn: 'fn_notice_add_audience',
    args: (ctx) => [
      reqStr(ctx.params.noticeId, 'noticeId'),
      reqStr(ctx.body.audience, 'audience'),
      ctx.body.batch_id ?? null,
    ],
    paramsSchema: obj({ noticeId: uuid }, ['noticeId']),
    request: obj(
      {
        audience: { type: 'string', enum: ['PUBLIC', 'APPLICANTS', 'STUDENTS', 'BATCH'] },
        batch_id: { ...uuid, nullable: true },
      },
      ['audience'],
    ),
    response: obj({ audience_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.VAL.FAILED'],
  },
  {
    domain: 'centre-administration',
    opId: 'notice.publish',
    method: 'POST',
    path: '/admin/notices/:noticeId/publish',
    auth: 'user',
    summary: 'Publish a DRAFT notice (centre_admin).',
    fn: 'fn_notice_publish',
    args: (ctx) => [reqStr(ctx.params.noticeId, 'noticeId')],
    paramsSchema: obj({ noticeId: uuid }, ['noticeId']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.VAL.FAILED'],
  },
];
