// domain: hostel (request → approve → allocate/transfer/discharge; bed status)
import type { Operation } from '../operation.js';
import { reqStr } from '../operation.js';
import { obj, uuid, okResult } from '../schemas.js';

export const hostelOps: Operation[] = [
  {
    domain: 'hostel',
    opId: 'hostel.request',
    method: 'POST',
    path: '/enrolments/:enrolmentId/hostel-request',
    auth: 'user',
    summary: 'Student requests hostel accommodation for their enrolment.',
    fn: 'fn_hostel_request',
    successStatus: 201,
    args: (ctx) => [reqStr(ctx.params.enrolmentId, 'enrolmentId')],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    response: obj({ request_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.ALREADY_ACTIVE'],
    notes: 'One live request per enrolment (ux_hostel_request_live); re-request allowed after cancel/discharge.',
  },
  {
    domain: 'hostel',
    opId: 'hostel.cancel_request',
    method: 'POST',
    path: '/hostel/requests/:requestId/cancel',
    auth: 'user',
    summary: 'Student cancels a pre-allocation hostel request.',
    fn: 'fn_hostel_cancel',
    args: (ctx) => [reqStr(ctx.params.requestId, 'requestId')],
    paramsSchema: obj({ requestId: uuid }, ['requestId']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'hostel',
    opId: 'hostel.approve',
    method: 'POST',
    path: '/hostel/requests/:requestId/approve',
    auth: 'user',
    summary: 'Hostel manager approves a request (APPROVED if beds free, else QUEUED).',
    fn: 'fn_hostel_approve',
    args: (ctx) => [reqStr(ctx.params.requestId, 'requestId')],
    paramsSchema: obj({ requestId: uuid }, ['requestId']),
    response: obj({ status: { type: 'string', enum: ['APPROVED', 'QUEUED'] } }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'hostel',
    opId: 'hostel.allocate',
    method: 'POST',
    path: '/hostel/requests/:requestId/allocate',
    auth: 'user',
    summary: 'Hostel manager allocates a specific bed (concurrency-safe, idempotent).',
    fn: 'fn_hostel_allocate',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.requestId, 'requestId'), reqStr(ctx.body.bed_id, 'bed_id')],
    paramsSchema: obj({ requestId: uuid }, ['requestId']),
    request: obj({ bed_id: uuid }, ['bed_id']),
    response: obj({ allocated: { type: 'boolean' } }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.CONFLICT.ALREADY_ACTIVE'],
    notes: 'Bed locked first (rank 2). One active allocation per bed/enrolment (SEC-CONC-003).',
  },
  {
    domain: 'hostel',
    opId: 'hostel.transfer',
    method: 'POST',
    path: '/enrolments/:enrolmentId/hostel-transfer',
    auth: 'user',
    summary: 'Transfer a resident to another bed (release+allocate in one tx, idempotent).',
    fn: 'fn_hostel_transfer',
    idempotent: true,
    args: (ctx) => [
      reqStr(ctx.params.enrolmentId, 'enrolmentId'),
      reqStr(ctx.body.to_bed, 'to_bed'),
      reqStr(ctx.body.reason, 'reason'),
    ],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    request: obj({ to_bed: uuid, reason: { type: 'string' } }, ['to_bed', 'reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.ALREADY_ACTIVE'],
    notes: 'Beds locked in ascending id order (deadlock-safe, §V-13).',
  },
  {
    domain: 'hostel',
    opId: 'hostel.discharge',
    method: 'POST',
    path: '/hostel/allocations/:allocationId/discharge',
    auth: 'user',
    summary: 'Discharge a resident; frees the bed and closes the request (idempotent).',
    fn: 'fn_hostel_discharge',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.allocationId, 'allocationId'), reqStr(ctx.body.reason, 'reason')],
    paramsSchema: obj({ allocationId: uuid }, ['allocationId']),
    request: obj({ reason: { type: 'string' } }, ['reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'hostel',
    opId: 'hostel.set_bed_status',
    method: 'POST',
    path: '/hostel/beds/:bedId/status',
    auth: 'user',
    summary: 'Toggle a bed AVAILABLE/MAINTENANCE (not while actively allocated).',
    fn: 'fn_set_bed_status',
    args: (ctx) => [reqStr(ctx.params.bedId, 'bedId'), reqStr(ctx.body.status, 'status')],
    paramsSchema: obj({ bedId: uuid }, ['bedId']),
    request: obj({ status: { type: 'string', enum: ['AVAILABLE', 'MAINTENANCE'] } }, ['status']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.ALREADY_ACTIVE', 'E.VAL.FAILED'],
  },
  // --- inventory CRUD (migration 0004) ---
  {
    domain: 'hostel',
    opId: 'hostel.block_create',
    method: 'POST',
    path: '/hostel/blocks',
    auth: 'user',
    summary: 'Create a hostel block (hostel_manager/centre_admin at the centre).',
    fn: 'fn_hostel_block_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.centre_id, 'centre_id'),
      reqStr(ctx.body.name, 'name'),
      ctx.body.warden_profile_id ?? null,
    ],
    request: obj(
      { centre_id: uuid, name: { type: 'string' }, warden_profile_id: { ...uuid, nullable: true } },
      ['centre_id', 'name'],
    ),
    response: obj({ block_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.VAL.FAILED'],
  },
  {
    domain: 'hostel',
    opId: 'hostel.room_create',
    method: 'POST',
    path: '/hostel/blocks/:blockId/rooms',
    auth: 'user',
    summary: 'Create a room in a block (hostel_manager/centre_admin).',
    fn: 'fn_room_create',
    successStatus: 201,
    args: (ctx) => [reqStr(ctx.params.blockId, 'blockId'), reqStr(ctx.body.room_no, 'room_no')],
    paramsSchema: obj({ blockId: uuid }, ['blockId']),
    request: obj({ room_no: { type: 'string' } }, ['room_no']),
    response: obj({ room_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE', 'E.VAL.FAILED'],
  },
  {
    domain: 'hostel',
    opId: 'hostel.bed_create',
    method: 'POST',
    path: '/hostel/rooms/:roomId/beds',
    auth: 'user',
    summary: 'Create a bed in a room (hostel_manager/centre_admin; starts AVAILABLE).',
    fn: 'fn_bed_create',
    successStatus: 201,
    args: (ctx) => [reqStr(ctx.params.roomId, 'roomId'), reqStr(ctx.body.bed_no, 'bed_no')],
    paramsSchema: obj({ roomId: uuid }, ['roomId']),
    request: obj({ bed_no: { type: 'string' } }, ['bed_no']),
    response: obj({ bed_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE', 'E.VAL.FAILED'],
  },
  // --- reads ---
  {
    domain: 'hostel',
    opId: 'hostel.requests.list',
    method: 'GET',
    path: '/enrolments/:enrolmentId/hostel-requests',
    auth: 'user',
    summary: 'List hostel requests for an enrolment (student self / hostel manager).',
    read: (ctx) => ({
      text: `SELECT id, enrolment_id, status, created_at, updated_at
             FROM app.hostel_requests WHERE enrolment_id = $1 ORDER BY created_at DESC`,
      values: [reqStr(ctx.params.enrolmentId, 'enrolmentId')],
    }),
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    notes: 'Scoped by policy p_hreq_sel.',
  },
];
