// domain: joining (offer accept/decline, enrolment lifecycle, expiry jobs)
import type { Operation } from '../operation.js';
import { reqStr } from '../operation.js';
import { obj, uuid, okResult } from '../schemas.js';

export const joiningOps: Operation[] = [
  {
    domain: 'joining',
    opId: 'offer.accept',
    method: 'POST',
    path: '/offers/:offerId/accept',
    auth: 'user',
    summary: 'Applicant accepts an admission offer → enrolment (seat-safe, idempotent).',
    fn: 'fn_offer_accept',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.offerId, 'offerId')],
    paramsSchema: obj({ offerId: uuid }, ['offerId']),
    response: obj({ enrolment_id: uuid, student_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.CONFLICT.DUPLICATE'],
    notes: 'Locks batch before offer (K order). Creates student + enrolment + hostel request if required.',
  },
  {
    domain: 'joining',
    opId: 'offer.decline',
    method: 'POST',
    path: '/offers/:offerId/decline',
    auth: 'user',
    summary: 'Applicant declines an admission offer (releases the seat).',
    fn: 'fn_offer_decline',
    args: (ctx) => [reqStr(ctx.params.offerId, 'offerId')],
    paramsSchema: obj({ offerId: uuid }, ['offerId']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'joining',
    opId: 'enrolment.confirm_joining',
    method: 'POST',
    path: '/enrolments/:enrolmentId/confirm-joining',
    auth: 'user',
    summary: 'Staff confirms the student joined (ENROLLED → ACTIVE).',
    fn: 'fn_confirm_joining',
    args: (ctx) => [reqStr(ctx.params.enrolmentId, 'enrolmentId')],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'joining',
    opId: 'enrolment.mark_not_joined',
    method: 'POST',
    path: '/enrolments/:enrolmentId/not-joined',
    auth: 'user',
    summary: 'Centre admin marks an enrolment not-joined (releases seat, idempotent).',
    fn: 'fn_mark_not_joined',
    idempotent: true,
    args: (ctx) => [reqStr(ctx.params.enrolmentId, 'enrolmentId'), reqStr(ctx.body.reason, 'reason')],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    request: obj({ reason: { type: 'string' } }, ['reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'joining',
    opId: 'enrolment.transfer',
    method: 'POST',
    path: '/enrolments/:enrolmentId/transfer',
    auth: 'user',
    summary: 'Transfer an enrolment to another batch (capacity-checked, idempotent).',
    fn: 'fn_transfer_enrolment',
    idempotent: true,
    args: (ctx) => [
      reqStr(ctx.params.enrolmentId, 'enrolmentId'),
      reqStr(ctx.body.to_batch, 'to_batch'),
      reqStr(ctx.body.reason, 'reason'),
    ],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    request: obj({ to_batch: uuid, reason: { type: 'string' } }, ['to_batch', 'reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION', 'E.CONFLICT.CAPACITY_FULL'],
  },
  {
    domain: 'joining',
    opId: 'enrolment.complete',
    method: 'POST',
    path: '/enrolments/:enrolmentId/complete',
    auth: 'user',
    summary: 'Centre admin completes an active enrolment.',
    fn: 'fn_complete_enrolment',
    args: (ctx) => [reqStr(ctx.params.enrolmentId, 'enrolmentId')],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'joining',
    opId: 'enrolment.drop',
    method: 'POST',
    path: '/enrolments/:enrolmentId/drop',
    auth: 'user',
    summary: 'Centre admin drops an enrolment (releases bed + hostel request + seat).',
    fn: 'fn_drop_enrolment',
    args: (ctx) => [reqStr(ctx.params.enrolmentId, 'enrolmentId'), reqStr(ctx.body.reason, 'reason')],
    paramsSchema: obj({ enrolmentId: uuid }, ['enrolmentId']),
    request: obj({ reason: { type: 'string' } }, ['reason']),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.STATE.INVALID_TRANSITION'],
  },
  {
    domain: 'joining',
    opId: 'jobs.expire_offers',
    method: 'POST',
    path: '/jobs/expire-offers',
    auth: 'service',
    summary: 'Scheduled job: expire SENT offers past expiry ([SYS]).',
    fn: 'fn_jobs_expire_offers',
    args: () => [],
    response: { type: 'integer', description: 'number of offers expired' },
    notes: 'service_role scheduler. Emits seat-released events for promotion.',
  },
  {
    domain: 'joining',
    opId: 'jobs.expire_drafts',
    method: 'POST',
    path: '/jobs/expire-drafts',
    auth: 'service',
    summary: 'Scheduled job: expire stale DRAFT applications ([SYS]).',
    fn: 'fn_jobs_expire_drafts',
    args: () => [],
    response: { type: 'integer', description: 'number of drafts expired' },
  },
  // --- reads ---
  {
    domain: 'joining',
    opId: 'offers.list',
    method: 'GET',
    path: '/applications/:id/offers',
    auth: 'user',
    summary: 'List admission offers for an application (owner or centre admin).',
    read: (ctx) => ({
      text: `SELECT id, application_id, batch_id, status, expires_at, created_at
             FROM app.admission_offers WHERE application_id = $1 ORDER BY created_at DESC`,
      values: [reqStr(ctx.params.id, 'id')],
    }),
    paramsSchema: obj({ id: uuid }, ['id']),
    notes: 'Scoped by policy p_offers_sel.',
  },
  {
    domain: 'joining',
    opId: 'enrolments.list',
    method: 'GET',
    path: '/enrolments',
    auth: 'user',
    summary: 'List enrolments visible to the caller (student self / batch staff / trainer).',
    read: () => ({
      text: `SELECT id, student_id, batch_id, application_id, status, joined_at, left_at, created_at
             FROM app.enrolments ORDER BY created_at DESC LIMIT 200`,
      values: [],
    }),
    notes: 'Scoped by policy p_enrol_sel.',
  },
];
