// domain: placement (consent profile, referrals, outcomes)
import type { Operation } from '../operation.js';
import { reqStr } from '../operation.js';
import { obj, uuid, isoDate, okResult } from '../schemas.js';

export const placementOps: Operation[] = [
  {
    domain: 'placement',
    opId: 'placement.create_profile',
    method: 'POST',
    path: '/placement/profile',
    auth: 'user',
    summary: 'Student creates a placement profile (structural consent: consent_at set).',
    fn: 'fn_placement_profile_create',
    successStatus: 201,
    args: (ctx) => [ctx.body.skills_summary ?? null, ctx.body.preferred_district ?? null],
    request: obj({
      skills_summary: { type: 'string', nullable: true },
      preferred_district: { type: 'string', nullable: true },
    }),
    response: obj({ profile_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.ALREADY_ACTIVE'],
  },
  {
    domain: 'placement',
    opId: 'placement.withdraw_consent',
    method: 'POST',
    path: '/placement/profile/withdraw',
    auth: 'user',
    summary: 'Student withdraws placement consent (closes open referrals).',
    fn: 'fn_placement_withdraw',
    args: () => [],
    response: okResult,
    errors: ['E.RES.NOT_FOUND'],
  },
  {
    domain: 'placement',
    opId: 'referral.create',
    method: 'POST',
    path: '/placement/opportunities/:opportunityId/referrals',
    auth: 'user',
    summary: 'Placement staff refers a consented student to an opportunity.',
    fn: 'fn_referral_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.params.opportunityId, 'opportunityId'),
      reqStr(ctx.body.placement_profile_id, 'placement_profile_id'),
    ],
    paramsSchema: obj({ opportunityId: uuid }, ['opportunityId']),
    request: obj({ placement_profile_id: uuid }, ['placement_profile_id']),
    response: obj({ referral_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE'],
    notes: 'Consented (non-withdrawn) profiles only (C9).',
  },
  {
    domain: 'placement',
    opId: 'referral.update_status',
    method: 'PATCH',
    path: '/placement/referrals/:referralId',
    auth: 'user',
    summary: 'Placement staff updates a referral status.',
    fn: 'fn_referral_status',
    args: (ctx) => [reqStr(ctx.params.referralId, 'referralId'), reqStr(ctx.body.status, 'status')],
    paramsSchema: obj({ referralId: uuid }, ['referralId']),
    request: obj(
      { status: { type: 'string', enum: ['INTERVIEW', 'OFFERED', 'DECLINED', 'CLOSED'] } },
      ['status'],
    ),
    response: okResult,
    errors: ['E.RES.NOT_FOUND', 'E.VAL.FAILED'],
  },
  {
    domain: 'placement',
    opId: 'outcome.record',
    method: 'POST',
    path: '/placement/referrals/:referralId/outcome',
    auth: 'user',
    summary: 'Placement staff records a placement outcome (assistance record; never guaranteed).',
    fn: 'fn_outcome_record',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.params.referralId, 'referralId'),
      reqStr(ctx.body.outcome, 'outcome'),
      ctx.body.joined_on ?? null,
      ctx.body.salary_band ?? null,
    ],
    paramsSchema: obj({ referralId: uuid }, ['referralId']),
    request: obj(
      {
        outcome: { type: 'string', enum: ['JOINED', 'NOT_JOINED'] },
        joined_on: { ...isoDate, nullable: true },
        salary_band: { type: 'string', nullable: true },
      },
      ['outcome'],
    ),
    response: obj({ outcome_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.CONFLICT.DUPLICATE', 'E.VAL.FAILED'],
  },
  // --- catalogue CRUD (migration 0004) ---
  {
    domain: 'placement',
    opId: 'employer.create',
    method: 'POST',
    path: '/placement/employers',
    auth: 'user',
    summary: 'Create an employer (placement/centre_admin staff).',
    fn: 'fn_employer_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.name, 'name'),
      ctx.body.contact ?? null,
      ctx.body.district ?? null,
    ],
    request: obj(
      {
        name: { type: 'string' },
        contact: { type: 'string', nullable: true },
        district: { type: 'string', nullable: true },
      },
      ['name'],
    ),
    response: obj({ employer_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.VAL.FAILED'],
  },
  {
    domain: 'placement',
    opId: 'opportunity.create',
    method: 'POST',
    path: '/placement/opportunities',
    auth: 'user',
    summary: 'Create a placement opportunity (placement/centre_admin at the centre).',
    fn: 'fn_opportunity_create',
    successStatus: 201,
    args: (ctx) => [
      reqStr(ctx.body.employer_id, 'employer_id'),
      reqStr(ctx.body.centre_id, 'centre_id'),
      ctx.body.course_id ?? null,
      reqStr(ctx.body.title, 'title'),
      Number(ctx.body.openings ?? 0),
      ctx.body.closes_on ?? null,
    ],
    request: obj(
      {
        employer_id: uuid,
        centre_id: uuid,
        course_id: { ...uuid, nullable: true },
        title: { type: 'string' },
        openings: { type: 'integer', minimum: 1 },
        closes_on: { type: 'string', format: 'date', nullable: true },
      },
      ['employer_id', 'centre_id', 'title', 'openings'],
    ),
    response: obj({ opportunity_id: uuid }),
    errors: ['E.RES.NOT_FOUND', 'E.VAL.FAILED'],
  },
  // --- reads ---
  {
    domain: 'placement',
    opId: 'placement.opportunities.list',
    method: 'GET',
    path: '/placement/opportunities',
    auth: 'user',
    summary: 'List job opportunities visible to the caller (staff / consented student).',
    read: () => ({
      text: `SELECT id, employer_id, centre_id, course_id, title, openings, closes_on, created_at
             FROM app.job_opportunities ORDER BY created_at DESC LIMIT 200`,
      values: [],
    }),
    notes: 'Scoped by policy p_opp_sel.',
  },
  {
    domain: 'placement',
    opId: 'placement.referrals.list',
    method: 'GET',
    path: '/placement/referrals',
    auth: 'user',
    summary: 'List referrals visible to the caller (student self / placement staff).',
    read: () => ({
      text: `SELECT id, opportunity_id, placement_profile_id, status, created_at, updated_at
             FROM app.placement_referrals ORDER BY created_at DESC LIMIT 200`,
      values: [],
    }),
    notes: 'Scoped by policy p_ref_sel.',
  },
];
