// GENERATED by scripts/convert-handoff.mjs — do not edit by hand.
import * as s0 from "./generated/about";
import * as s1 from "./generated/admin-admissions";
import * as s2 from "./generated/admin-applications";
import * as s3 from "./generated/admin-assessments";
import * as s4 from "./generated/admin-certificates";
import * as s5 from "./generated/admin-dashboard";
import * as s6 from "./generated/admin-directory";
import * as s7 from "./generated/admin-hostel";
import * as s8 from "./generated/admin-industry";
import * as s9 from "./generated/admin-programs";
import * as s10 from "./generated/admin-reports";
import * as s11 from "./generated/admin-settings";
import * as s12 from "./generated/application";
import * as s13 from "./generated/assessments";
import * as s14 from "./generated/attendance";
import * as s15 from "./generated/campus";
import * as s16 from "./generated/certificates";
import * as s17 from "./generated/contact";
import * as s18 from "./generated/counselling";
import * as s19 from "./generated/dashboard";
import * as s20 from "./generated/documents";
import * as s21 from "./generated/home";
import * as s22 from "./generated/hostel";
import * as s23 from "./generated/index";
import * as s24 from "./generated/login";
import * as s25 from "./generated/notifications";
import * as s26 from "./generated/placement";
import * as s27 from "./generated/profile";
import * as s28 from "./generated/register";
import * as s29 from "./generated/schemes";
import * as s30 from "./generated/sitemap";
import * as s31 from "./generated/staff-attendance";
import * as s32 from "./generated/staff-dashboard";
import * as s33 from "./generated/staff-directory";
import * as s34 from "./generated/staff-hostel";
import * as s35 from "./generated/staff-placement";
import * as s36 from "./generated/staff-reports";
import * as s37 from "./generated/student-dashboard";
import * as s38 from "./generated/student-profile";
import * as s39 from "./generated/support";
import * as s40 from "./generated/timeline";
import * as s41 from "./generated/verification";

export interface Screen { portal: string; title: string; html: string; css: string; }
export const SCREENS: Record<string, Screen> = {
  "about": s0,
  "admin-admissions": s1,
  "admin-applications": s2,
  "admin-assessments": s3,
  "admin-certificates": s4,
  "admin-dashboard": s5,
  "admin-directory": s6,
  "admin-hostel": s7,
  "admin-industry": s8,
  "admin-programs": s9,
  "admin-reports": s10,
  "admin-settings": s11,
  "application": s12,
  "assessments": s13,
  "attendance": s14,
  "campus": s15,
  "certificates": s16,
  "contact": s17,
  "counselling": s18,
  "dashboard": s19,
  "documents": s20,
  "home": s21,
  "hostel": s22,
  "index": s23,
  "login": s24,
  "notifications": s25,
  "placement": s26,
  "profile": s27,
  "register": s28,
  "schemes": s29,
  "sitemap": s30,
  "staff-attendance": s31,
  "staff-dashboard": s32,
  "staff-directory": s33,
  "staff-hostel": s34,
  "staff-placement": s35,
  "staff-reports": s36,
  "student-dashboard": s37,
  "student-profile": s38,
  "support": s39,
  "timeline": s40,
  "verification": s41,
};
export const SCREEN_NAMES = Object.keys(SCREENS);
