// convert-handoff.mjs — extract each handoff screen (app/*.html) into a generated TS module
// exporting { html, css, portal, title }. We keep the screen's exact body markup verbatim
// (high fidelity) and strip only the prototype-only bits the README says to replace:
//   - the CDN Tailwind <script> and the inline `tailwind.config` script (compiled build instead)
//   - support.js and the inline nav-shim <script> (real Next.js routing instead)
//   - <style> blocks are extracted and re-injected scoped by <HandoffScreen>.
// Images: none ship in the bundle (screens use gradients + icon glyphs), so nothing to localize.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "../../_frontend_integration/design_handoff_sjkvy_ecosystem/app");
const OUT = join(here, "../src/screens/generated");
mkdirSync(OUT, { recursive: true });

function bodyInner(html) {
  const m = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  return m ? m[1] : html;
}
function portalOf(html) {
  const m = html.match(/<body[^>]*\bdata-portal="([^"]*)"/i);
  return m ? m[1] : "public";
}
function titleOf(html) {
  const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return m ? m[1].replace(/&amp;/g, "&").trim() : "";
}
function allStyles(html) {
  const out = [];
  for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)) out.push(m[1]);
  return out.join("\n").trim();
}
function stripTag(html, tag) {
  return html.replace(new RegExp(`<${tag}[\\s\\S]*?<\\/${tag}>`, "gi"), "");
}
function esc(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const files = readdirSync(SRC).filter((f) => f.endsWith(".html")).sort();
const names = [];
let count = 0;
for (const file of files) {
  const raw = readFileSync(join(SRC, file), "utf8");
  const name = basename(file, ".html");
  const portal = portalOf(raw);
  const title = titleOf(raw);
  const css = allStyles(raw);
  let body = bodyInner(raw);
  body = stripTag(body, "script"); // drop nav-shim / inline scripts (re-wired in React)
  body = stripTag(body, "style"); // extracted above, re-injected scoped
  body = body.trim();
  const out = `// GENERATED from handoff app/${file} — do not edit by hand. Regenerate: npm run convert
export const portal = ${JSON.stringify(portal)};
export const title = ${JSON.stringify(title)};
export const html = \`${esc(body)}\`;
export const css = \`${esc(css)}\`;
`;
  writeFileSync(join(OUT, `${name}.ts`), out);
  names.push(name);
  count++;
}

// registry.ts — maps every screen name to its module + metadata, for the dynamic route.
const imports = names.map((n, i) => `import * as s${i} from "./generated/${n}";`).join("\n");
const entries = names.map((n, i) => `  ${JSON.stringify(n)}: s${i},`).join("\n");
const registry = `// GENERATED by scripts/convert-handoff.mjs — do not edit by hand.
${imports}

export interface Screen { portal: string; title: string; html: string; css: string; }
export const SCREENS: Record<string, Screen> = {
${entries}
};
export const SCREEN_NAMES = Object.keys(SCREENS);
`;
writeFileSync(join(here, "../src/screens/registry.ts"), registry);
console.log(`converted ${count} screens -> src/screens/generated/ (+ registry.ts)`);
